use std::collections::HashMap;
use std::fs;
use std::path::{Path, PathBuf};

use tracing::{info, warn};
use zip::write::FileOptions;

use crate::EngineError;

// ---------------------------------------------------------------------------
// Cargo project scaffolder
// ---------------------------------------------------------------------------

/// Writes a bare-bones Cargo workspace / binary crate to `workspace_path`.
pub struct Scaffolder {
    pub workspace_path: PathBuf,
    pub crate_name: String,
}

impl Scaffolder {
    pub fn new(workspace_path: PathBuf, crate_name: String) -> Self {
        Self {
            workspace_path,
            crate_name,
        }
    }

    /// Create the directory skeleton.
    pub fn scaffold(&self) -> Result<(), EngineError> {
        let src = self.workspace_path.join("src");
        fs::create_dir_all(&src).map_err(|e| EngineError::Io(e.to_string()))?;

        // Minimal Cargo.toml
        let cargo_toml = format!(
            r#"[package]
name = "{name}"
version = "0.1.0"
edition = "2021"

[dependencies]
serde       = {{ version = "1", features = ["derive"] }}
serde_json  = "1"
thiserror   = "1"
anyhow      = "1"
tokio       = {{ version = "1", features = ["full"] }}
reqwest     = {{ version = "0.12", features = ["json"] }}
tracing     = "0.1"
tracing-subscriber = "0.3"
"#,
            name = self.crate_name
        );
        fs::write(self.workspace_path.join("Cargo.toml"), cargo_toml)
            .map_err(|e| EngineError::Io(e.to_string()))?;

        // Placeholder main so the project compiles before translation.
        let placeholder = "fn main() { println!(\"Rustyfi: translation in progress\"); }\n";
        fs::write(src.join("main.rs"), placeholder)
            .map_err(|e| EngineError::Io(e.to_string()))?;

        info!("Scaffolded crate at {}", self.workspace_path.display());
        Ok(())
    }

    /// Write a translated source file into the correct module path.
    /// `rel_path` is the path of the source file relative to the original
    /// workspace root; we map it into `src/`.
    pub fn write_module(
        &self,
        rel_path: &Path,
        rust_code: &str,
        extra_deps: &HashMap<String, String>,
    ) -> Result<PathBuf, EngineError> {
        // Map the source file to a Rust path.
        let rust_name = rust_module_name(rel_path);
        let dest = self.workspace_path.join("src").join(&rust_name);

        if let Some(parent) = dest.parent() {
            fs::create_dir_all(parent).map_err(|e| EngineError::Io(e.to_string()))?;
        }
        fs::write(&dest, rust_code).map_err(|e| EngineError::Io(e.to_string()))?;

        // Merge any additional deps the LLM declared.
        if !extra_deps.is_empty() {
            self.merge_deps(extra_deps)?;
        }

        Ok(dest)
    }

    /// Regenerate main.rs to wire up translated modules.
    pub fn write_main(&self, modules: &[String]) -> Result<(), EngineError> {
        let mut src = String::new();
        for m in modules {
            src.push_str(&format!("pub mod {m};\n"));
        }
        src.push_str("\nfn main() {\n    // Generated by Rustyfi\n    println!(\"Rustyfi translation complete\");\n}\n");
        let path = self.workspace_path.join("src").join("main.rs");
        fs::write(&path, src).map_err(|e| EngineError::Io(e.to_string()))?;
        Ok(())
    }

    /// Append extra dependencies to the project's Cargo.toml.
    fn merge_deps(&self, extra: &HashMap<String, String>) -> Result<(), EngineError> {
        let path = self.workspace_path.join("Cargo.toml");
        let mut content = fs::read_to_string(&path).map_err(|e| EngineError::Io(e.to_string()))?;

        for (krate, ver) in extra {
            // Skip if already present.
            if content.contains(&format!("\n{krate}")) {
                continue;
            }
            warn!("Adding dep from LLM hint: {krate} = \"{ver}\"");
            content.push_str(&format!("{krate} = \"{ver}\"\n"));
        }

        fs::write(&path, content).map_err(|e| EngineError::Io(e.to_string()))?;
        Ok(())
    }
}

// ---------------------------------------------------------------------------
// Module name mapper
// ---------------------------------------------------------------------------

fn rust_module_name(source_path: &Path) -> PathBuf {
    // Strip the original extension and replace it with .rs.
    let stem = source_path
        .file_stem()
        .map(|s| s.to_string_lossy().to_lowercase())
        .unwrap_or_else(|| "module".into());

    // Sanitise the stem to be a valid Rust identifier.
    let safe: String = stem
        .chars()
        .map(|c| if c.is_alphanumeric() || c == '_' { c } else { '_' })
        .collect();

    let safe = if safe.starts_with(|c: char| c.is_ascii_digit()) {
        format!("m_{safe}")
    } else {
        safe
    };

    PathBuf::from(format!("{safe}.rs"))
}

// ---------------------------------------------------------------------------
// ZIP packager
// ---------------------------------------------------------------------------

/// Zip up the entire workspace directory into a single bytes buffer.
pub fn package_to_zip(workspace_path: &Path) -> Result<Vec<u8>, EngineError> {
    use std::io::Write;
    use zip::CompressionMethod;

    let buf = Vec::new();
    let cursor = std::io::Cursor::new(buf);
    let mut zip = zip::ZipWriter::new(cursor);

    let opts: FileOptions<()> = FileOptions::default()
        .compression_method(CompressionMethod::Deflated)
        .unix_permissions(0o644);

    let workspace_root = workspace_path
        .file_name()
        .map(|n| n.to_string_lossy().to_string())
        .unwrap_or_else(|| "rustyfi_output".to_string());

    for entry in walkdir::WalkDir::new(workspace_path)
        .into_iter()
        .filter_map(|e| e.ok())
    {
        let path = entry.path();
        let rel = path
            .strip_prefix(workspace_path)
            .unwrap_or(path)
            .to_string_lossy();
        let zip_path = format!("{workspace_root}/{rel}");

        if path.is_dir() {
            zip.add_directory(&zip_path, opts)
                .map_err(|e| EngineError::Io(e.to_string()))?;
        } else {
            // Skip target/ directory — it's huge.
            if zip_path.contains("/target/") {
                continue;
            }
            zip.start_file(&zip_path, opts)
                .map_err(|e| EngineError::Io(e.to_string()))?;
            let data = fs::read(path).map_err(|e| EngineError::Io(e.to_string()))?;
            zip.write_all(&data)
                .map_err(|e| EngineError::Io(e.to_string()))?;
        }
    }

    let cursor = zip.finish().map_err(|e| EngineError::Io(e.to_string()))?;
    Ok(cursor.into_inner())
}
